export const GET_USER_PENDING = "GET_USER_PENDING";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const GET_PRODUCT_PENDING = "GET_PRODUCT_PENDING";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED";

export const GET_DETAIL_PRODUCT_PENDING = "GET_DETAIL_PRODUCT_PENDING";
export const GET_DETAIL_PRODUCT_SUCCESS = "GET_DETAIL_PRODUCT_SUCCESS";
export const GET_DETAIL_PRODUCT_FAILED = "GET_DETAIL_PRODUCT_FAILED";

export const GET_DETAIL_BOOKING_PENDING = "GET_DETAIL_BOOKING_PENDING";
export const GET_DETAIL_BOOKING_SUCCESS = "GET_DETAIL_BOOKING_SUCCESS";
export const GET_DETAIL_BOOKING_FAILED = "GET_DETAIL_BOOKING_FAILED";

export const GET_DETAIL_USER_PENDING = "GET_DETAIL_USER_PENDING";
export const GET_DETAIL_USER_SUCCESS = "GET_DETAIL_USER_SUCCESS";
export const GET_DETAIL_USER_FAILED = "GET_DETAIL_USER_FAILED";

export const GET_AIRLINE_PENDING = "GET_AIRLINE_PENDING";
export const GET_AIRLINE_SUCCESS = "GET_AIRLINE_SUCCESS";
export const GET_AIRLINE_FAILED = "GET_AIRLINE_FAILED";

export const GET_DESTINATION_PENDING = "GET_DESTINATION_PENDING";
export const GET_DESTINATION_SUCCESS = "GET_DESTINATION_SUCCESS";
export const GET_DESTINATION_FAILED = "GET_DESTINATION_FAILED";

export const GET_OLDDESTINATION_PENDING = "GET_OLDDESTINATION_PENDING";
export const GET_OLDDESTINATION_SUCCESS = "GET_OLDDESTINATION_SUCCESS";
export const GET_OLDDESTINATION_FAILED = "GET_OLDDESTINATION_FAILED";

export const SET_PASSENGER_DATA = "SET_PASSENGER_DATA";

export const GET_MYBOOKING_PENDING = "GET_MYBOOKING_PENDING";
export const GET_MYBOOKING_SUCCESS = "GET_MYBOOKING_SUCCESS";
export const GET_MYBOOKING_FAILED = "GET_DESTINATION_FAILED";

